[package]
edition = "2021"
name = "diode"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
rtic = { version = "2", features = ["thumbv7-backend"] }

# Basic set
embassy-futures = { version = "0.1.0" }
embassy-sync = { version = "0.2.0", features = ["defmt"] }
embassy-time = { version = "0.1.2", features = ["nightly", "unstable-traits", "defmt", "defmt-timestamp-uptime", "generic-queue"] }
embassy-stm32 = { version = "0.1.0", features = ["nightly", "unstable-traits", "defmt", "time-driver-any", "unstable-pac", "time", "stm32f411ce"] }

# Additional
embassy-usb = { version = "0.1.0", features = ["defmt"] }
static_cell = { version = "1.1", features = ["nightly"]}


defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
futures = { version = "0.3.17", default-features = false, features = ["async-await"] }

[patch.crates-io]
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "b0da6318f3eaa4a7fa247834ae5d95887c5bcf18" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "b0da6318f3eaa4a7fa247834ae5d95887c5bcf18" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "b0da6318f3eaa4a7fa247834ae5d95887c5bcf18" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", rev = "b0da6318f3eaa4a7fa247834ae5d95887c5bcf18" }

embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "b0da6318f3eaa4a7fa247834ae5d95887c5bcf18" }
